import {
	FaGithub,
	FaLinkedin,
	FaRegBookmark,
	FaRegUser,
} from 'react-icons/fa';
import { FaXTwitter } from 'react-icons/fa6';
import { IoGridOutline } from 'react-icons/io5';
import type { Project } from '../types';

export const personalInfo = {
	name: 'Kintarō Ōe',
	age: 25,
	location: 'Tokio, Japón',
	occupation: 'Full-Stack Developer & Traveling Tech Enthusiast',
	overview:
		'A mis 25 años deje atrás la universidad para aprender de la vida en la práctica! Hoy, tras recorrer Japón de norte a sur, domino tecnologías front-end y back-end, y sigo buscando proyectos que me reten.',
	socialLinks: [
		{
			id: 1,
			name: 'GitHub',
			url: '',
			icon: <FaGithub size={26} />,
		},
		{
			id: 2,
			name: 'LinkedIn',
			url: '',
			icon: <FaLinkedin size={26} />,
		},
		{
			id: 3,
			name: 'Twitter',
			url: '',
			icon: <FaXTwitter size={26} />,
		},
	],
	contactEmail: 'kintaro@gmail.com',
	phoneNumber: '+81 90-1234-5678',
	photoSrc: '/foto.png',
};

export const tabs = [
	{
		id: 1,
		name: 'Proyectos',
		icon: IoGridOutline,
	},
	{
		id: 2,
		name: 'Experiencia',
		icon: FaRegBookmark,
	},
	{
		id: 3,
		name: 'Habilidades',
		icon: FaRegUser,
	},
];

export const projects: Project[] = [
	{
		id: 1,
		name: 'QuickOS',
		description:
			'Un sistema operativo minimalista inspirado en el episodio OVA donde Kintarō rehace toda la plataforma: interfaz modular, lanzador de apps y accesos rápidos, diseñado para ser intuitivo incluso para novatos.',
		technologies: [
			'Rust',
			'WebAssembly',
			'Electron',
			'React',
			'Tailwind CSS',
			'GraphQL',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project_1.png',
	},
	{
		id: 2,
		name: 'TutorAI',
		description:
			'Plataforma de tutoría inteligente que analiza el código del alumno en tiempo real y sugiere correcciones; nace de la habilidad de Kintarō para aprender ultra rápido y enseñar a otros.',
		technologies: [
			'Next.js',
			'TensorFlow.js',
			'Socket.IO',
			'TypeScript',
			'Supabase',
			'Docker',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project_2.png',
	},
	{
		id: 3,
		name: 'TaskForge',
		description:
			'App de gestión de tareas con gamificación: cada “misión” se desbloquea cuando completas retos de código; rinde homenaje al estilo de entrenamiento de Kintarō con chalecos de peso.',
		technologies: [
			'Flutter',
			'Firebase (Firestore, Auth)',
			'GitHub Actions',
			'Node.js',
			'NestJS',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project_3.jpeg',
	},
	{
		id: 4,
		name: 'Pictogram Adventure',
		description:
			'Juego educativo que combina rutas de aprendizaje basadas en pictogramas (inspirado en Arasaac) con una narrativa de viaje por Japón, como las andanzas de Kintarō.',
		technologies: [
			'Unity',
			'C#',
			'REST API (Arasaac)',
			'PlayFab',
			'GSAP',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project_4.jpeg',
	},
	{
		id: 5,
		name: 'AnimeSearch Pro',
		description:
			'Motor de búsqueda avanzada de OVAs y series clásicas con IA para recomendaciones personalizadas; incluye un “modo Golden Boy” que muestra curiosidades del manga.',
		technologies: [
			'Python',
			'FastAPI',
			'Elasticsearch',
			'Vue.js',
			'Tailwind CSS',
			'OpenAI API',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project_5.png',
	},
	{
		id: 6,
		name: 'MapMyJourney',
		description:
			'Webapp de mapas interactivos donde registras tus viajes (al estilo de Kintarō en bicicleta) y generas un diario de código y fotos con IA para resúmenes automáticos.',
		technologies: [
			'Gatsby',
			'Mapbox GL',
			'Contentful',
			'Cloudinary',
			'Node.js',
			'AWS Lambda',
		],
		projectUrl: '',
		githubUrl: '',
		imageSrc: '/project_6.jpeg',
	},
];

export const experience = [
	{
		id: 1,
		position: 'Lead Front-End Developer',
		timeRange: 'Ene 2023 – Jun 2025',
		companyName: 'SpringTech Inc.',
		companyLocation: 'Tokio, Japón',
		description:
			'Lideré la migración de un monolito React a micro-frontends con Module Federation; mejoré accesibilidad (WCAG 2.1) y performance (Lighthouse > 90).',
		technologiesUsed: [
			'React',
			'Webpack Module Federation',
			'Storybook',
			'Lighthouse',
		],
	},
	{
		id: 2,
		position: 'Full-Stack Freelance',
		timeRange: 'Jul 2020 – Dic 2022',
		companyName: 'Varios clientes startup',
		companyLocation: 'Remoto',
		description:
			'Entregué más de 15 proyectos: e-commerce, dashboards y APIs REST/GraphQL; monté pipelines CI/CD en AWS y DigitalOcean.',
		technologiesUsed: ['Node.js', 'NestJS', 'AWS', 'GitHub Actions'],
	},
	{
		id: 3,
		position: 'Instructor React & GSAP',
		timeRange: '2018 – 2020',
		companyName: 'CodeCamp Japón',
		companyLocation: 'Online',
		description:
			'Diseñé y dicté cursos de animaciones avanzadas con GSAP en React, usando miniaturas al estilo Golden Boy con chalecos de aprendizaje.',
		technologiesUsed: ['React', 'GSAP', 'Tailwind CSS', 'Figma'],
	},
];

export const skills = [
	{
		id: 1,
		imageSrc: '/react.png',
		technologyName: 'React',
		level: 'Avanzado',
		context: 'Frontend',
		bgColor: '#E1F5FE',
		borderColor: '#81D4FA',
	},
	{
		id: 2,
		imageSrc: '/nextjs.png',
		technologyName: 'Next.js',
		level: 'Intermedio',
		context: 'Full-Stack',
		bgColor: '#F5F5F5',
		borderColor: '#BDBDBD',
	},
	{
		id: 3,
		imageSrc: '/nodejs.png',
		technologyName: 'Node.js',
		level: 'Avanzado',
		context: 'Backend',
		bgColor: '#E8F5E8',
		borderColor: '#81C784',
	},
	{
		id: 4,
		imageSrc: '/nestjs.png',
		technologyName: 'NestJS',
		level: 'Avanzado',
		context: 'Backend',
		bgColor: '#FCE4EC',
		borderColor: '#F48FB1',
	},
	{
		id: 5,
		imageSrc: '/gsap.png',
		technologyName: 'GSAP',
		level: 'Intermedio',
		context: 'Animations',
		bgColor: '#F1F8E9',
		borderColor: '#AED581',
	},
	{
		id: 6,
		imageSrc: '/tailwindcss.png',
		technologyName: 'Tailwind CSS',
		level: 'Avanzado',
		context: 'UI/UX',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
	{
		id: 7,
		imageSrc: '/typescript.png',
		technologyName: 'TypeScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 8,
		imageSrc: '/javascript.png',
		technologyName: 'JavaScript',
		level: 'Avanzado',
		context: 'Language',
		bgColor: '#FFFDE7',
		borderColor: '#FFF176',
	},
	{
		id: 9,
		imageSrc: '/python.png',
		technologyName: 'Python',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 10,
		imageSrc: '/rust.png',
		technologyName: 'Rust',
		level: 'Básico',
		context: 'Systems',
		bgColor: '#FFF3E0',
		borderColor: '#FFCC80',
	},
	{
		id: 11,
		imageSrc: '/flutter.png',
		technologyName: 'Flutter',
		level: 'Intermedio',
		context: 'Mobile',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 12,
		imageSrc: '/vuejs.png',
		technologyName: 'Vue.js',
		level: 'Intermedio',
		context: 'Frontend',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 13,
		imageSrc: '/graphql.png',
		technologyName: 'GraphQL',
		level: 'Intermedio',
		context: 'API',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 14,
		imageSrc: '/docker.png',
		technologyName: 'Docker',
		level: 'Intermedio',
		context: 'DevOps',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 15,
		imageSrc: '/aws.png',
		technologyName: 'AWS',
		level: 'Intermedio',
		context: 'Cloud',
		bgColor: '#FFF8E1',
		borderColor: '#FFCC02',
	},
	{
		id: 16,
		imageSrc: '/firebase.png',
		technologyName: 'Firebase',
		level: 'Avanzado',
		context: 'Backend',
		bgColor: '#FFF8E1',
		borderColor: '#FFD54F',
	},
	{
		id: 17,
		imageSrc: '/mongodb.png',
		technologyName: 'MongoDB',
		level: 'Avanzado',
		context: 'Database',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 18,
		imageSrc: '/postgresql.png',
		technologyName: 'PostgreSQL',
		level: 'Intermedio',
		context: 'Database',
		bgColor: '#E3F2FD',
		borderColor: '#90CAF9',
	},
	{
		id: 19,
		imageSrc: '/unity.png',
		technologyName: 'Unity',
		level: 'Básico',
		context: 'Game Dev',
		bgColor: '#FAFAFA',
		borderColor: '#E0E0E0',
	},
	{
		id: 20,
		imageSrc: '/csharp.png',
		technologyName: 'C#',
		level: 'Básico',
		context: 'Language',
		bgColor: '#E8F5E8',
		borderColor: '#A5D6A7',
	},
	{
		id: 21,
		imageSrc: '/storybook.png',
		technologyName: 'Storybook',
		level: 'Intermedio',
		context: 'UI Tools',
		bgColor: '#FCE4EC',
		borderColor: '#F8BBD9',
	},
	{
		id: 22,
		imageSrc: '/fastapi.png',
		technologyName: 'FastAPI',
		level: 'Intermedio',
		context: 'Backend',
		bgColor: '#E0F2F1',
		borderColor: '#80CBC4',
	},
	{
		id: 23,
		imageSrc: '/elasticsearch.png',
		technologyName: 'Elasticsearch',
		level: 'Básico',
		context: 'Search',
		bgColor: '#E0F7FA',
		borderColor: '#80DEEA',
	},
];
